env: # Environt variable to pass to all tasks
    CIRRUS_CLONE_DEPTH: 1 # No need to clone with whole history
    CIRRUS_WORKING_DIR: "/tmp/ci" # Where to clone repo
    rclone_config: "ENCRYPTED[fc7c8110f8d1a43aadee340ed2e2924374b2548502521f6c77b7732cca4e6c0c1969a4cae1d3a4096bfac0fa164668f2]"
task:
  name: "CIRRUS SSH"
  timeout_in: 960m  
  container:
      image: ubuntu:latest
      cpu: 8
      memory: 32G
  download_ccache_script:
      - bash download_ccache
  Setup_script:
      - export DEBIAN_FRONTEND=noninteractive
      - apt update
      - apt install sudo
      - df -h
      - DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends tzdata
      - ln -sf /usr/share/zoneinfo/Asia/Kolkata /etc/localtime
      - sudo apt-get install git -y
      - git clone https://github.com/akhilnarang/scripts
      - cd scripts
      - bash setup/android_build_env.sh
      - repo init -u https://github.com/Havoc-OS/android_manifest.git -b eleven
      - repo sync -c -j$(nproc --all) --force-sync --no-clone-bundle --no-tags
  install_rclone_script: 
      - curl https://rclone.org/install.sh | sudo bash
      - curl -O https://downloads.rclone.org/rclone-current-linux-amd64.zip
      - unzip rclone-current-linux-amd64.zip
      - cd rclone-*-linux-amd64
  install_pigz_scripts:
      - sudo apt install pigz
  upit_script:
      - bash upit
